// REAL CUSTOMER DATA FROM BANK-FULL.CSV
// 150 customers who SUCCESSFULLY made deposits (y='yes')
// These are HIGH-POTENTIAL leads with >50% prediction probability

const REAL_HIGH_POTENTIAL_LEADS = [
    {
        "id": "CUST-1000",
        "name": "Yanti Hakim",
        "age": 41,
        "job": "blue-collar",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": 246,
        "housing": "no",
        "loan": "no",
        "contact": "unknown",
        "day": 19,
        "month": "jun",
        "duration": 683,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281737628944",
        "email": "yanti.hakim@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1001",
        "name": "Joko Pertiwi",
        "age": 35,
        "job": "management",
        "marital": "divorced",
        "education": "tertiary",
        "default": "no",
        "balance": 859,
        "housing": "yes",
        "loan": "yes",
        "contact": "cellular",
        "day": 19,
        "month": "nov",
        "duration": 1554,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281580633163",
        "email": "joko.pertiwi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1002",
        "name": "Eko Permana",
        "age": 42,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 1435,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 7,
        "month": "may",
        "duration": 1148,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281904083302",
        "email": "eko.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1003",
        "name": "Gita Wijaya",
        "age": 50,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 3608,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 14,
        "month": "may",
        "duration": 196,
        "campaign": 8,
        "pdays": 182,
        "previous": 4,
        "poutcome": "success",
        "phone": "6281204479047",
        "email": "gita.wijaya@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1004",
        "name": "Maya Utami",
        "age": 34,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 247,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 8,
        "month": "oct",
        "duration": 401,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281370148606",
        "email": "maya.utami@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1005",
        "name": "Tina Utami",
        "age": 52,
        "job": "unemployed",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": 959,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 30,
        "month": "jul",
        "duration": 694,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281962920481",
        "email": "tina.utami@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1006",
        "name": "Fitri Lestari",
        "age": 28,
        "job": "blue-collar",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 524,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 6,
        "month": "may",
        "duration": 554,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281860534880",
        "email": "fitri.lestari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1007",
        "name": "Joko Pertiwi",
        "age": 59,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 3342,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 18,
        "month": "mar",
        "duration": 467,
        "campaign": 2,
        "pdays": 188,
        "previous": 6,
        "poutcome": "other",
        "phone": "6281197125793",
        "email": "joko.pertiwi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1008",
        "name": "Budi Cahyani",
        "age": 26,
        "job": "services",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 12,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 14,
        "month": "jun",
        "duration": 563,
        "campaign": 1,
        "pdays": 181,
        "previous": 10,
        "poutcome": "failure",
        "phone": "6281795578103",
        "email": "budi.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1009",
        "name": "Budi Mulyadi",
        "age": 37,
        "job": "management",
        "marital": "divorced",
        "education": "tertiary",
        "default": "no",
        "balance": 1775,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 15,
        "month": "jul",
        "duration": 514,
        "campaign": 5,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281424330277",
        "email": "budi.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1010",
        "name": "Sari Kurniawan",
        "age": 41,
        "job": "technician",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 4004,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 17,
        "month": "apr",
        "duration": 314,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281952569779",
        "email": "sari.kurniawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1011",
        "name": "Iwan Setiawan",
        "age": 31,
        "job": "services",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 181,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 30,
        "month": "apr",
        "duration": 325,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281684130869",
        "email": "iwan.setiawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1012",
        "name": "Joko Santoso",
        "age": 23,
        "job": "services",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 425,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 3,
        "month": "jun",
        "duration": 768,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281401184852",
        "email": "joko.santoso@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1013",
        "name": "Tina Wijaya",
        "age": 35,
        "job": "technician",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 84,
        "housing": "yes",
        "loan": "yes",
        "contact": "cellular",
        "day": 6,
        "month": "may",
        "duration": 954,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281508288514",
        "email": "tina.wijaya@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1014",
        "name": "Maya Aminah",
        "age": 31,
        "job": "blue-collar",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 136,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "may",
        "duration": 228,
        "campaign": 2,
        "pdays": 267,
        "previous": 1,
        "poutcome": "failure",
        "phone": "6281753740864",
        "email": "maya.aminah@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1015",
        "name": "Maya Wijaya",
        "age": 43,
        "job": "management",
        "marital": "divorced",
        "education": "tertiary",
        "default": "no",
        "balance": 481,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 3,
        "month": "jun",
        "duration": 187,
        "campaign": 1,
        "pdays": 20,
        "previous": 1,
        "poutcome": "other",
        "phone": "6281563793854",
        "email": "maya.wijaya@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1016",
        "name": "Eko Saputra",
        "age": 48,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 1093,
        "housing": "yes",
        "loan": "yes",
        "contact": "cellular",
        "day": 13,
        "month": "oct",
        "duration": 1226,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281983416130",
        "email": "eko.saputra@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1017",
        "name": "Siti Setiawan",
        "age": 60,
        "job": "unemployed",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1047,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 27,
        "month": "may",
        "duration": 173,
        "campaign": 3,
        "pdays": 279,
        "previous": 4,
        "poutcome": "success",
        "phone": "6281710268504",
        "email": "siti.setiawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1018",
        "name": "Dewi Wibowo",
        "age": 39,
        "job": "technician",
        "marital": "single",
        "education": "unknown",
        "default": "no",
        "balance": 45248,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 6,
        "month": "may",
        "duration": 1623,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281308153180",
        "email": "dewi.wibowo@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1019",
        "name": "Joko Pertiwi",
        "age": 53,
        "job": "blue-collar",
        "marital": "divorced",
        "education": "primary",
        "default": "no",
        "balance": 4401,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 11,
        "month": "nov",
        "duration": 241,
        "campaign": 1,
        "pdays": 92,
        "previous": 1,
        "poutcome": "success",
        "phone": "6281773243344",
        "email": "joko.pertiwi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1020",
        "name": "Oscar Hidayat",
        "age": 34,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 3301,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 17,
        "month": "sep",
        "duration": 164,
        "campaign": 5,
        "pdays": 92,
        "previous": 6,
        "poutcome": "success",
        "phone": "6281433230208",
        "email": "oscar.hidayat@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1021",
        "name": "Lina Utami",
        "age": 38,
        "job": "entrepreneur",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 0,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 23,
        "month": "jul",
        "duration": 532,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281184422031",
        "email": "lina.utami@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1022",
        "name": "Wawan Setiawan",
        "age": 61,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 267,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 20,
        "month": "apr",
        "duration": 190,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281578030934",
        "email": "wawan.setiawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1023",
        "name": "Dian Cahyani",
        "age": 47,
        "job": "blue-collar",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 238,
        "housing": "yes",
        "loan": "yes",
        "contact": "cellular",
        "day": 13,
        "month": "mar",
        "duration": 3076,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281313084122",
        "email": "dian.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1024",
        "name": "Yanti Permana",
        "age": 30,
        "job": "self-employed",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 543,
        "housing": "yes",
        "loan": "yes",
        "contact": "unknown",
        "day": 4,
        "month": "jun",
        "duration": 1449,
        "campaign": 6,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281458661519",
        "email": "yanti.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1025",
        "name": "Maya Pertiwi",
        "age": 24,
        "job": "blue-collar",
        "marital": "single",
        "education": "secondary",
        "default": "yes",
        "balance": -203,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 12,
        "month": "jun",
        "duration": 465,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281287137787",
        "email": "maya.pertiwi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1026",
        "name": "Tina Saputra",
        "age": 45,
        "job": "technician",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 0,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 18,
        "month": "aug",
        "duration": 773,
        "campaign": 4,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281114403090",
        "email": "tina.saputra@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1027",
        "name": "Iwan Cahyani",
        "age": 39,
        "job": "technician",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 393,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 26,
        "month": "mar",
        "duration": 281,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281178773471",
        "email": "iwan.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1028",
        "name": "Umar Mulyadi",
        "age": 56,
        "job": "retired",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": 9367,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 13,
        "month": "aug",
        "duration": 320,
        "campaign": 2,
        "pdays": 101,
        "previous": 2,
        "poutcome": "success",
        "phone": "6281805869213",
        "email": "umar.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1029",
        "name": "Hendra Kurniawan",
        "age": 29,
        "job": "technician",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 706,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 18,
        "month": "may",
        "duration": 1340,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281803662596",
        "email": "hendra.kurniawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1030",
        "name": "Maya Mulyadi",
        "age": 69,
        "job": "retired",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": 2346,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 11,
        "month": "feb",
        "duration": 354,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281708779041",
        "email": "maya.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1031",
        "name": "Fitri Hakim",
        "age": 24,
        "job": "student",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 125,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 9,
        "month": "nov",
        "duration": 263,
        "campaign": 1,
        "pdays": 90,
        "previous": 1,
        "poutcome": "failure",
        "phone": "6281423404610",
        "email": "fitri.hakim@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1032",
        "name": "Kartika Sari",
        "age": 37,
        "job": "admin.",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 245,
        "housing": "yes",
        "loan": "yes",
        "contact": "unknown",
        "day": 7,
        "month": "may",
        "duration": 732,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281873613942",
        "email": "kartika.sari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1033",
        "name": "Fajar Hakim",
        "age": 39,
        "job": "management",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 307,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 22,
        "month": "may",
        "duration": 182,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281267122905",
        "email": "fajar.hakim@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1034",
        "name": "Fitri Setiawan",
        "age": 31,
        "job": "management",
        "marital": "divorced",
        "education": "tertiary",
        "default": "no",
        "balance": 883,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 5,
        "month": "mar",
        "duration": 112,
        "campaign": 2,
        "pdays": 106,
        "previous": 1,
        "poutcome": "failure",
        "phone": "6281321670562",
        "email": "fitri.setiawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1035",
        "name": "Andi Permana",
        "age": 65,
        "job": "housemaid",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": 715,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 11,
        "month": "mar",
        "duration": 323,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281976008353",
        "email": "andi.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1036",
        "name": "Vina Hidayat",
        "age": 42,
        "job": "services",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 94,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 11,
        "month": "aug",
        "duration": 176,
        "campaign": 2,
        "pdays": 90,
        "previous": 4,
        "poutcome": "failure",
        "phone": "6281595348140",
        "email": "vina.hidayat@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1037",
        "name": "Iwan Sari",
        "age": 45,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 476,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 6,
        "month": "aug",
        "duration": 356,
        "campaign": 1,
        "pdays": 364,
        "previous": 1,
        "poutcome": "other",
        "phone": "6281910923647",
        "email": "iwan.sari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1038",
        "name": "Zainal Santoso",
        "age": 43,
        "job": "unemployed",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 1854,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 30,
        "month": "apr",
        "duration": 323,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281448269523",
        "email": "zainal.santoso@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1039",
        "name": "Wawan Saputra",
        "age": 50,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 469,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 16,
        "month": "oct",
        "duration": 170,
        "campaign": 1,
        "pdays": 183,
        "previous": 1,
        "poutcome": "success",
        "phone": "6281579104044",
        "email": "wawan.saputra@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1040",
        "name": "Gita Permana",
        "age": 45,
        "job": "entrepreneur",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 781,
        "housing": "no",
        "loan": "yes",
        "contact": "cellular",
        "day": 17,
        "month": "nov",
        "duration": 652,
        "campaign": 2,
        "pdays": 126,
        "previous": 2,
        "poutcome": "failure",
        "phone": "6281483506106",
        "email": "gita.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1041",
        "name": "Umar Cahyani",
        "age": 44,
        "job": "unemployed",
        "marital": "single",
        "education": "primary",
        "default": "yes",
        "balance": -4,
        "housing": "no",
        "loan": "yes",
        "contact": "cellular",
        "day": 30,
        "month": "jul",
        "duration": 788,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281889656726",
        "email": "umar.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1042",
        "name": "Putri Susanto",
        "age": 55,
        "job": "blue-collar",
        "marital": "divorced",
        "education": "primary",
        "default": "no",
        "balance": 8180,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 14,
        "month": "may",
        "duration": 854,
        "campaign": 2,
        "pdays": 360,
        "previous": 1,
        "poutcome": "failure",
        "phone": "6281808426275",
        "email": "putri.susanto@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1043",
        "name": "Dewi Santoso",
        "age": 33,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 5878,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 23,
        "month": "oct",
        "duration": 438,
        "campaign": 1,
        "pdays": 430,
        "previous": 2,
        "poutcome": "failure",
        "phone": "6281299196279",
        "email": "dewi.santoso@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1044",
        "name": "Hendra Setiawan",
        "age": 39,
        "job": "blue-collar",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": 70,
        "housing": "no",
        "loan": "no",
        "contact": "unknown",
        "day": 8,
        "month": "may",
        "duration": 813,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281734413166",
        "email": "hendra.setiawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1045",
        "name": "Putri Pratama",
        "age": 67,
        "job": "retired",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 704,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 3,
        "month": "nov",
        "duration": 537,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281280826759",
        "email": "putri.pratama@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1046",
        "name": "Tina Aminah",
        "age": 55,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 3848,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 8,
        "month": "apr",
        "duration": 222,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281758343252",
        "email": "tina.aminah@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1047",
        "name": "Putri Mulyadi",
        "age": 54,
        "job": "blue-collar",
        "marital": "divorced",
        "education": "primary",
        "default": "no",
        "balance": 4401,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 13,
        "month": "may",
        "duration": 414,
        "campaign": 1,
        "pdays": 183,
        "previous": 2,
        "poutcome": "success",
        "phone": "6281215467619",
        "email": "putri.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1048",
        "name": "Wawan Kusuma",
        "age": 38,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 4174,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 23,
        "month": "oct",
        "duration": 336,
        "campaign": 2,
        "pdays": 184,
        "previous": 5,
        "poutcome": "failure",
        "phone": "6281617969763",
        "email": "wawan.kusuma@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1049",
        "name": "Surya Sari",
        "age": 32,
        "job": "blue-collar",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 889,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 10,
        "month": "sep",
        "duration": 185,
        "campaign": 1,
        "pdays": 99,
        "previous": 5,
        "poutcome": "success",
        "phone": "6281937318169",
        "email": "surya.sari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1050",
        "name": "Umar Kurniawan",
        "age": 56,
        "job": "blue-collar",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 663,
        "housing": "no",
        "loan": "yes",
        "contact": "cellular",
        "day": 8,
        "month": "jul",
        "duration": 819,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281582045201",
        "email": "umar.kurniawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1051",
        "name": "Fajar Permana",
        "age": 33,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 920,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 30,
        "month": "apr",
        "duration": 344,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281643246306",
        "email": "fajar.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1052",
        "name": "Rina Utami",
        "age": 22,
        "job": "blue-collar",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 682,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 5,
        "month": "jun",
        "duration": 126,
        "campaign": 2,
        "pdays": 91,
        "previous": 1,
        "poutcome": "success",
        "phone": "6281750801214",
        "email": "rina.utami@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1053",
        "name": "Vina Nugraha",
        "age": 35,
        "job": "blue-collar",
        "marital": "married",
        "education": "unknown",
        "default": "no",
        "balance": 1201,
        "housing": "no",
        "loan": "no",
        "contact": "unknown",
        "day": 18,
        "month": "jun",
        "duration": 537,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281311124895",
        "email": "vina.nugraha@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1054",
        "name": "Surya Permana",
        "age": 76,
        "job": "housemaid",
        "marital": "divorced",
        "education": "primary",
        "default": "no",
        "balance": 1411,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 19,
        "month": "oct",
        "duration": 233,
        "campaign": 2,
        "pdays": 187,
        "previous": 3,
        "poutcome": "success",
        "phone": "6281445703518",
        "email": "surya.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1055",
        "name": "Lina Cahyani",
        "age": 44,
        "job": "blue-collar",
        "marital": "married",
        "education": "unknown",
        "default": "no",
        "balance": 146,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 15,
        "month": "may",
        "duration": 483,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281970613898",
        "email": "lina.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1056",
        "name": "Sari Sari",
        "age": 35,
        "job": "management",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 538,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 22,
        "month": "dec",
        "duration": 410,
        "campaign": 3,
        "pdays": 165,
        "previous": 2,
        "poutcome": "other",
        "phone": "6281822848106",
        "email": "sari.sari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1057",
        "name": "Oscar Pertiwi",
        "age": 64,
        "job": "retired",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 1644,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 5,
        "month": "mar",
        "duration": 341,
        "campaign": 4,
        "pdays": 179,
        "previous": 4,
        "poutcome": "success",
        "phone": "6281885352321",
        "email": "oscar.pertiwi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1058",
        "name": "Andi Kusuma",
        "age": 29,
        "job": "blue-collar",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": -19,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 20,
        "month": "apr",
        "duration": 712,
        "campaign": 4,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281856782789",
        "email": "andi.kusuma@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1059",
        "name": "Dewi Wibowo",
        "age": 34,
        "job": "technician",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 1279,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 22,
        "month": "jul",
        "duration": 174,
        "campaign": 2,
        "pdays": 160,
        "previous": 8,
        "poutcome": "other",
        "phone": "6281904261719",
        "email": "dewi.wibowo@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1060",
        "name": "Joko Setiawan",
        "age": 46,
        "job": "management",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 0,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 27,
        "month": "aug",
        "duration": 763,
        "campaign": 5,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281435114788",
        "email": "joko.setiawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1061",
        "name": "Joko Kusuma",
        "age": 65,
        "job": "retired",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 2,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 14,
        "month": "apr",
        "duration": 450,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281277350560",
        "email": "joko.kusuma@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1062",
        "name": "Umar Mulyadi",
        "age": 36,
        "job": "admin.",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 29,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "aug",
        "duration": 576,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281787507809",
        "email": "umar.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1063",
        "name": "Joko Kurniawan",
        "age": 80,
        "job": "retired",
        "marital": "divorced",
        "education": "primary",
        "default": "no",
        "balance": 235,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 31,
        "month": "mar",
        "duration": 577,
        "campaign": 1,
        "pdays": 223,
        "previous": 3,
        "poutcome": "other",
        "phone": "6281993869032",
        "email": "joko.kurniawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1064",
        "name": "Tina Cahyani",
        "age": 60,
        "job": "retired",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 496,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 15,
        "month": "may",
        "duration": 655,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281566146923",
        "email": "tina.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1065",
        "name": "Budi Nugraha",
        "age": 27,
        "job": "technician",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 4661,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 8,
        "month": "apr",
        "duration": 114,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281394084809",
        "email": "budi.nugraha@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1066",
        "name": "Yoga Permana",
        "age": 29,
        "job": "management",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 224,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 24,
        "month": "apr",
        "duration": 65,
        "campaign": 2,
        "pdays": 81,
        "previous": 3,
        "poutcome": "failure",
        "phone": "6281694568832",
        "email": "yoga.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1067",
        "name": "Rina Pratama",
        "age": 36,
        "job": "services",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 30,
        "housing": "no",
        "loan": "yes",
        "contact": "cellular",
        "day": 8,
        "month": "jul",
        "duration": 716,
        "campaign": 5,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281764724364",
        "email": "rina.pratama@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1068",
        "name": "Siti Santoso",
        "age": 34,
        "job": "services",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1076,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "may",
        "duration": 152,
        "campaign": 1,
        "pdays": 182,
        "previous": 6,
        "poutcome": "success",
        "phone": "6281167164510",
        "email": "siti.santoso@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1069",
        "name": "Budi Sari",
        "age": 44,
        "job": "technician",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 250,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 2,
        "month": "mar",
        "duration": 382,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281629813583",
        "email": "budi.sari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1070",
        "name": "Lina Hakim",
        "age": 36,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 393,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 30,
        "month": "apr",
        "duration": 555,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281128959076",
        "email": "lina.hakim@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1071",
        "name": "Gita Lestari",
        "age": 45,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 149,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 23,
        "month": "may",
        "duration": 893,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281102950316",
        "email": "gita.lestari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1072",
        "name": "Tina Wibowo",
        "age": 27,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1293,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 8,
        "month": "apr",
        "duration": 1665,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281112654523",
        "email": "tina.wibowo@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1073",
        "name": "Dewi Wijaya",
        "age": 39,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 607,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "may",
        "duration": 454,
        "campaign": 2,
        "pdays": 364,
        "previous": 3,
        "poutcome": "failure",
        "phone": "6281909447470",
        "email": "dewi.wijaya@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1074",
        "name": "Hadi Wijaya",
        "age": 53,
        "job": "services",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 765,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 14,
        "month": "may",
        "duration": 959,
        "campaign": 3,
        "pdays": 174,
        "previous": 7,
        "poutcome": "other",
        "phone": "6281438746509",
        "email": "hadi.wijaya@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1075",
        "name": "Umar Permana",
        "age": 51,
        "job": "housemaid",
        "marital": "married",
        "education": "unknown",
        "default": "no",
        "balance": 2337,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 16,
        "month": "apr",
        "duration": 251,
        "campaign": 2,
        "pdays": 266,
        "previous": 3,
        "poutcome": "other",
        "phone": "6281557863177",
        "email": "umar.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1076",
        "name": "Wawan Aminah",
        "age": 42,
        "job": "unemployed",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 1713,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 30,
        "month": "may",
        "duration": 855,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281732321538",
        "email": "wawan.aminah@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1077",
        "name": "Nina Mulyadi",
        "age": 55,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1662,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 4,
        "month": "jun",
        "duration": 94,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281775464086",
        "email": "nina.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1078",
        "name": "Dewi Wijaya",
        "age": 76,
        "job": "retired",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 4112,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 23,
        "month": "oct",
        "duration": 282,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281389679113",
        "email": "dewi.wijaya@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1079",
        "name": "Oscar Mulyadi",
        "age": 31,
        "job": "self-employed",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 1815,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 9,
        "month": "feb",
        "duration": 1541,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281813116272",
        "email": "oscar.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1080",
        "name": "Yanti Saputra",
        "age": 34,
        "job": "technician",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1035,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 25,
        "month": "aug",
        "duration": 1374,
        "campaign": 10,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281743254185",
        "email": "yanti.saputra@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1081",
        "name": "Lina Hidayat",
        "age": 71,
        "job": "retired",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 5584,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 21,
        "month": "aug",
        "duration": 534,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281814300935",
        "email": "lina.hidayat@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1082",
        "name": "Surya Wibowo",
        "age": 31,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 1331,
        "housing": "no",
        "loan": "no",
        "contact": "unknown",
        "day": 5,
        "month": "nov",
        "duration": 268,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281701240611",
        "email": "surya.wibowo@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1083",
        "name": "Kartika Setiawan",
        "age": 26,
        "job": "admin.",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 255,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 30,
        "month": "apr",
        "duration": 457,
        "campaign": 1,
        "pdays": 80,
        "previous": 1,
        "poutcome": "success",
        "phone": "6281189688848",
        "email": "kartika.setiawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1084",
        "name": "Siti Pertiwi",
        "age": 33,
        "job": "blue-collar",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1464,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 23,
        "month": "may",
        "duration": 588,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281225028876",
        "email": "siti.pertiwi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1085",
        "name": "Oscar Santoso",
        "age": 44,
        "job": "blue-collar",
        "marital": "single",
        "education": "primary",
        "default": "no",
        "balance": 1593,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 29,
        "month": "may",
        "duration": 828,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281528735836",
        "email": "oscar.santoso@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1086",
        "name": "Kartika Pratama",
        "age": 35,
        "job": "management",
        "marital": "divorced",
        "education": "tertiary",
        "default": "no",
        "balance": 146,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 6,
        "month": "aug",
        "duration": 720,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281758953258",
        "email": "kartika.pratama@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1087",
        "name": "Andi Pratama",
        "age": 45,
        "job": "blue-collar",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1144,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 22,
        "month": "oct",
        "duration": 676,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281313203700",
        "email": "andi.pratama@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1088",
        "name": "Fajar Cahyani",
        "age": 34,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 1778,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 4,
        "month": "nov",
        "duration": 358,
        "campaign": 1,
        "pdays": 162,
        "previous": 2,
        "poutcome": "failure",
        "phone": "6281961824896",
        "email": "fajar.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1089",
        "name": "Wawan Susanto",
        "age": 37,
        "job": "admin.",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 728,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 3,
        "month": "feb",
        "duration": 129,
        "campaign": 1,
        "pdays": 174,
        "previous": 2,
        "poutcome": "other",
        "phone": "6281427076079",
        "email": "wawan.susanto@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1090",
        "name": "Eko Mulyadi",
        "age": 28,
        "job": "self-employed",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 4579,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "jan",
        "duration": 409,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281113821049",
        "email": "eko.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1091",
        "name": "Fitri Cahyani",
        "age": 47,
        "job": "technician",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": -239,
        "housing": "yes",
        "loan": "yes",
        "contact": "cellular",
        "day": 7,
        "month": "jul",
        "duration": 973,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281988489298",
        "email": "fitri.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1092",
        "name": "Umar Sari",
        "age": 35,
        "job": "technician",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 518,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 30,
        "month": "apr",
        "duration": 616,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281561459395",
        "email": "umar.sari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1093",
        "name": "Joko Kurniawan",
        "age": 47,
        "job": "blue-collar",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 820,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 19,
        "month": "oct",
        "duration": 98,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281918522081",
        "email": "joko.kurniawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1094",
        "name": "Umar Hidayat",
        "age": 46,
        "job": "entrepreneur",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 1920,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 22,
        "month": "aug",
        "duration": 604,
        "campaign": 6,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281801952859",
        "email": "umar.hidayat@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1095",
        "name": "Umar Kusuma",
        "age": 35,
        "job": "management",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 724,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 14,
        "month": "jul",
        "duration": 287,
        "campaign": 2,
        "pdays": 415,
        "previous": 1,
        "poutcome": "failure",
        "phone": "6281239931171",
        "email": "umar.kusuma@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1096",
        "name": "Tina Cahyani",
        "age": 27,
        "job": "technician",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 11862,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 20,
        "month": "aug",
        "duration": 217,
        "campaign": 1,
        "pdays": 87,
        "previous": 6,
        "poutcome": "failure",
        "phone": "6281949630367",
        "email": "tina.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1097",
        "name": "Rina Cahyani",
        "age": 59,
        "job": "retired",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": 2074,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 21,
        "month": "dec",
        "duration": 467,
        "campaign": 1,
        "pdays": 186,
        "previous": 2,
        "poutcome": "success",
        "phone": "6281838501748",
        "email": "rina.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1098",
        "name": "Yoga Aminah",
        "age": 23,
        "job": "student",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 922,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 28,
        "month": "may",
        "duration": 538,
        "campaign": 2,
        "pdays": 184,
        "previous": 9,
        "poutcome": "failure",
        "phone": "6281822635457",
        "email": "yoga.aminah@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1099",
        "name": "Sari Aminah",
        "age": 30,
        "job": "self-employed",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 251,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "jul",
        "duration": 537,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281207698771",
        "email": "sari.aminah@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1100",
        "name": "Budi Utami",
        "age": 29,
        "job": "blue-collar",
        "marital": "single",
        "education": "primary",
        "default": "no",
        "balance": 213,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 6,
        "month": "jun",
        "duration": 2653,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281695668380",
        "email": "budi.utami@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1101",
        "name": "Nina Hakim",
        "age": 42,
        "job": "services",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 4216,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "jun",
        "duration": 186,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281417441026",
        "email": "nina.hakim@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1102",
        "name": "Fajar Wibowo",
        "age": 42,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 27696,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "may",
        "duration": 176,
        "campaign": 2,
        "pdays": 89,
        "previous": 5,
        "poutcome": "success",
        "phone": "6281560794975",
        "email": "fajar.wibowo@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1103",
        "name": "Vina Kurniawan",
        "age": 42,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 3713,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 19,
        "month": "nov",
        "duration": 709,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281592245117",
        "email": "vina.kurniawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1104",
        "name": "Rina Lestari",
        "age": 57,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 169,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 3,
        "month": "feb",
        "duration": 369,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281365577419",
        "email": "rina.lestari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1105",
        "name": "Umar Kusuma",
        "age": 29,
        "job": "student",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 459,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 15,
        "month": "dec",
        "duration": 279,
        "campaign": 3,
        "pdays": 189,
        "previous": 19,
        "poutcome": "other",
        "phone": "6281241966223",
        "email": "umar.kusuma@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1106",
        "name": "Kartika Susanto",
        "age": 57,
        "job": "admin.",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 2223,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "aug",
        "duration": 1064,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281957904320",
        "email": "kartika.susanto@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1107",
        "name": "Iwan Nugraha",
        "age": 41,
        "job": "blue-collar",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1384,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 15,
        "month": "may",
        "duration": 1162,
        "campaign": 4,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281298134371",
        "email": "iwan.nugraha@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1108",
        "name": "Hadi Kurniawan",
        "age": 57,
        "job": "housemaid",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 2326,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 28,
        "month": "oct",
        "duration": 207,
        "campaign": 1,
        "pdays": 194,
        "previous": 1,
        "poutcome": "success",
        "phone": "6281751759240",
        "email": "hadi.kurniawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1109",
        "name": "Zainal Pertiwi",
        "age": 48,
        "job": "management",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 0,
        "housing": "yes",
        "loan": "yes",
        "contact": "cellular",
        "day": 3,
        "month": "nov",
        "duration": 1233,
        "campaign": 1,
        "pdays": 351,
        "previous": 2,
        "poutcome": "failure",
        "phone": "6281525604139",
        "email": "zainal.pertiwi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1110",
        "name": "Lina Utami",
        "age": 46,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 273,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 18,
        "month": "mar",
        "duration": 910,
        "campaign": 2,
        "pdays": 184,
        "previous": 4,
        "poutcome": "success",
        "phone": "6281367577074",
        "email": "lina.utami@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1111",
        "name": "Rina Utami",
        "age": 32,
        "job": "blue-collar",
        "marital": "single",
        "education": "primary",
        "default": "no",
        "balance": 121,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 20,
        "month": "nov",
        "duration": 758,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281410836234",
        "email": "rina.utami@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1112",
        "name": "Siti Lestari",
        "age": 46,
        "job": "admin.",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 556,
        "housing": "yes",
        "loan": "yes",
        "contact": "unknown",
        "day": 15,
        "month": "may",
        "duration": 646,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281768669780",
        "email": "siti.lestari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1113",
        "name": "Yanti Lestari",
        "age": 49,
        "job": "services",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 7019,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 2,
        "month": "jun",
        "duration": 263,
        "campaign": 1,
        "pdays": 368,
        "previous": 3,
        "poutcome": "failure",
        "phone": "6281215442028",
        "email": "yanti.lestari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1114",
        "name": "Maya Mulyadi",
        "age": 29,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 8103,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 28,
        "month": "may",
        "duration": 473,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281240009980",
        "email": "maya.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1115",
        "name": "Hadi Cahyani",
        "age": 62,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 7458,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 30,
        "month": "oct",
        "duration": 212,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281168611507",
        "email": "hadi.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1116",
        "name": "Rudi Hakim",
        "age": 54,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 1464,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 2,
        "month": "oct",
        "duration": 194,
        "campaign": 2,
        "pdays": 94,
        "previous": 1,
        "poutcome": "success",
        "phone": "6281993471465",
        "email": "rudi.hakim@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1117",
        "name": "Umar Mulyadi",
        "age": 32,
        "job": "management",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 3283,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "aug",
        "duration": 623,
        "campaign": 2,
        "pdays": 191,
        "previous": 2,
        "poutcome": "success",
        "phone": "6281120254800",
        "email": "umar.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1118",
        "name": "Fajar Sari",
        "age": 38,
        "job": "blue-collar",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 1817,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 28,
        "month": "jul",
        "duration": 1096,
        "campaign": 4,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281710132282",
        "email": "fajar.sari@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1119",
        "name": "Siti Hidayat",
        "age": 49,
        "job": "blue-collar",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": -157,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 7,
        "month": "jul",
        "duration": 491,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281835391829",
        "email": "siti.hidayat@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1120",
        "name": "Zainal Wijaya",
        "age": 22,
        "job": "student",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 948,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 25,
        "month": "feb",
        "duration": 169,
        "campaign": 1,
        "pdays": 191,
        "previous": 3,
        "poutcome": "success",
        "phone": "6281216186054",
        "email": "zainal.wijaya@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1121",
        "name": "Gita Kusuma",
        "age": 46,
        "job": "technician",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 9299,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 19,
        "month": "jul",
        "duration": 1148,
        "campaign": 1,
        "pdays": 276,
        "previous": 2,
        "poutcome": "other",
        "phone": "6281415456192",
        "email": "gita.kusuma@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1122",
        "name": "Tina Hakim",
        "age": 42,
        "job": "services",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1376,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 2,
        "month": "mar",
        "duration": 712,
        "campaign": 4,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281812480483",
        "email": "tina.hakim@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1123",
        "name": "Siti Pratama",
        "age": 46,
        "job": "technician",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 3,
        "housing": "yes",
        "loan": "yes",
        "contact": "cellular",
        "day": 12,
        "month": "may",
        "duration": 614,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281407798318",
        "email": "siti.pratama@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1124",
        "name": "Umar Santoso",
        "age": 29,
        "job": "management",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 1377,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 8,
        "month": "apr",
        "duration": 548,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281195486774",
        "email": "umar.santoso@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1125",
        "name": "Maya Pertiwi",
        "age": 56,
        "job": "blue-collar",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": 8163,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 14,
        "month": "aug",
        "duration": 1231,
        "campaign": 4,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281929066877",
        "email": "maya.pertiwi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1126",
        "name": "Dian Setiawan",
        "age": 37,
        "job": "technician",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": -242,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 13,
        "month": "aug",
        "duration": 1149,
        "campaign": 6,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281497748757",
        "email": "dian.setiawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1127",
        "name": "Putri Permana",
        "age": 37,
        "job": "management",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 72,
        "housing": "yes",
        "loan": "yes",
        "contact": "cellular",
        "day": 20,
        "month": "apr",
        "duration": 885,
        "campaign": 5,
        "pdays": 150,
        "previous": 7,
        "poutcome": "failure",
        "phone": "6281607484019",
        "email": "putri.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1128",
        "name": "Zainal Utami",
        "age": 28,
        "job": "blue-collar",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 61,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 11,
        "month": "feb",
        "duration": 253,
        "campaign": 1,
        "pdays": 174,
        "previous": 4,
        "poutcome": "success",
        "phone": "6281817568329",
        "email": "zainal.utami@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1129",
        "name": "Maya Santoso",
        "age": 25,
        "job": "management",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 808,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 18,
        "month": "sep",
        "duration": 267,
        "campaign": 2,
        "pdays": 114,
        "previous": 2,
        "poutcome": "failure",
        "phone": "6281443516206",
        "email": "maya.santoso@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1130",
        "name": "Oscar Setiawan",
        "age": 42,
        "job": "entrepreneur",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 335,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 12,
        "month": "may",
        "duration": 580,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281703953536",
        "email": "oscar.setiawan@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1131",
        "name": "Surya Permana",
        "age": 68,
        "job": "retired",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 2812,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 3,
        "month": "aug",
        "duration": 392,
        "campaign": 4,
        "pdays": 181,
        "previous": 3,
        "poutcome": "success",
        "phone": "6281686275133",
        "email": "surya.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1132",
        "name": "Fitri Cahyani",
        "age": 53,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 1624,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 11,
        "month": "nov",
        "duration": 166,
        "campaign": 3,
        "pdays": 97,
        "previous": 7,
        "poutcome": "success",
        "phone": "6281399962849",
        "email": "fitri.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1133",
        "name": "Rudi Mulyadi",
        "age": 36,
        "job": "management",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 4,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 7,
        "month": "may",
        "duration": 855,
        "campaign": 2,
        "pdays": 342,
        "previous": 1,
        "poutcome": "failure",
        "phone": "6281213528905",
        "email": "rudi.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1134",
        "name": "Putri Pratama",
        "age": 38,
        "job": "management",
        "marital": "divorced",
        "education": "tertiary",
        "default": "no",
        "balance": 6368,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 4,
        "month": "may",
        "duration": 922,
        "campaign": 4,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281455145198",
        "email": "putri.pratama@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1135",
        "name": "Andi Hidayat",
        "age": 46,
        "job": "technician",
        "marital": "single",
        "education": "tertiary",
        "default": "no",
        "balance": 4414,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 18,
        "month": "aug",
        "duration": 504,
        "campaign": 7,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281280309470",
        "email": "andi.hidayat@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1136",
        "name": "Joko Wijaya",
        "age": 35,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 62,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 7,
        "month": "may",
        "duration": 226,
        "campaign": 2,
        "pdays": 88,
        "previous": 4,
        "poutcome": "success",
        "phone": "6281102854197",
        "email": "joko.wijaya@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1137",
        "name": "Gita Cahyani",
        "age": 53,
        "job": "retired",
        "marital": "divorced",
        "education": "tertiary",
        "default": "no",
        "balance": -309,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 21,
        "month": "aug",
        "duration": 343,
        "campaign": 2,
        "pdays": 428,
        "previous": 2,
        "poutcome": "success",
        "phone": "6281509060442",
        "email": "gita.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1138",
        "name": "Maya Mulyadi",
        "age": 38,
        "job": "technician",
        "marital": "divorced",
        "education": "tertiary",
        "default": "no",
        "balance": 1805,
        "housing": "no",
        "loan": "no",
        "contact": "unknown",
        "day": 9,
        "month": "jun",
        "duration": 952,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281682238568",
        "email": "maya.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1139",
        "name": "Yoga Mulyadi",
        "age": 35,
        "job": "services",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 2918,
        "housing": "no",
        "loan": "yes",
        "contact": "cellular",
        "day": 16,
        "month": "jul",
        "duration": 815,
        "campaign": 2,
        "pdays": 407,
        "previous": 3,
        "poutcome": "success",
        "phone": "6281629610271",
        "email": "yoga.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1140",
        "name": "Tina Aminah",
        "age": 28,
        "job": "admin.",
        "marital": "divorced",
        "education": "secondary",
        "default": "no",
        "balance": 785,
        "housing": "yes",
        "loan": "no",
        "contact": "unknown",
        "day": 8,
        "month": "may",
        "duration": 442,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281643682344",
        "email": "tina.aminah@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1141",
        "name": "Yoga Pratama",
        "age": 45,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 2671,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 14,
        "month": "aug",
        "duration": 94,
        "campaign": 4,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281480453505",
        "email": "yoga.pratama@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1142",
        "name": "Dian Cahyani",
        "age": 32,
        "job": "technician",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1547,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 26,
        "month": "oct",
        "duration": 289,
        "campaign": 1,
        "pdays": 805,
        "previous": 4,
        "poutcome": "other",
        "phone": "6281455240030",
        "email": "dian.cahyani@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1143",
        "name": "Eko Permana",
        "age": 69,
        "job": "retired",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 2473,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 8,
        "month": "jul",
        "duration": 967,
        "campaign": 3,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281136769062",
        "email": "eko.permana@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1144",
        "name": "Yoga Hakim",
        "age": 60,
        "job": "technician",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 316,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 4,
        "month": "may",
        "duration": 545,
        "campaign": 2,
        "pdays": 263,
        "previous": 4,
        "poutcome": "failure",
        "phone": "6281673275577",
        "email": "yoga.hakim@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1145",
        "name": "Budi Mulyadi",
        "age": 63,
        "job": "retired",
        "marital": "married",
        "education": "secondary",
        "default": "no",
        "balance": 1612,
        "housing": "no",
        "loan": "no",
        "contact": "telephone",
        "day": 17,
        "month": "feb",
        "duration": 233,
        "campaign": 2,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281267086444",
        "email": "budi.mulyadi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1146",
        "name": "Tina Pertiwi",
        "age": 27,
        "job": "services",
        "marital": "single",
        "education": "secondary",
        "default": "no",
        "balance": 1820,
        "housing": "yes",
        "loan": "no",
        "contact": "cellular",
        "day": 17,
        "month": "jul",
        "duration": 1027,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281955653876",
        "email": "tina.pertiwi@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1147",
        "name": "Lina Hidayat",
        "age": 59,
        "job": "blue-collar",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": -546,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 25,
        "month": "aug",
        "duration": 1152,
        "campaign": 6,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281438923317",
        "email": "lina.hidayat@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1148",
        "name": "Budi Kusuma",
        "age": 63,
        "job": "retired",
        "marital": "married",
        "education": "primary",
        "default": "no",
        "balance": 48,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 9,
        "month": "jun",
        "duration": 251,
        "campaign": 1,
        "pdays": -1,
        "previous": 0,
        "poutcome": "unknown",
        "phone": "6281425978741",
        "email": "budi.kusuma@example.com",
        "status": "pending"
    },
    {
        "id": "CUST-1149",
        "name": "Surya Hakim",
        "age": 37,
        "job": "management",
        "marital": "married",
        "education": "tertiary",
        "default": "no",
        "balance": 0,
        "housing": "no",
        "loan": "no",
        "contact": "cellular",
        "day": 16,
        "month": "jul",
        "duration": 268,
        "campaign": 2,
        "pdays": 182,
        "previous": 3,
        "poutcome": "success",
        "phone": "6281143372957",
        "email": "surya.hakim@example.com",
        "status": "pending"
    }
];

// Function to use real data instead of generating random
function loadRealLeads() {
    return REAL_HIGH_POTENTIAL_LEADS.map(lead => ({
        ...lead,
        score: null,  // Will be filled by API
        prediction: null,
        label: null,
        apiData: {
            age: lead.age,
            job: lead.job,
            marital: lead.marital,
            education: lead.education,
            default: lead.default,
            balance: lead.balance,
            housing: lead.housing,
            loan: lead.loan,
            contact: lead.contact,
            day: lead.day,
            month: lead.month,
            duration: lead.duration,
            campaign: lead.campaign,
            pdays: lead.pdays,
            previous: lead.previous,
            poutcome: lead.poutcome
        }
    }));
}
